"""Stream a remote container's rootfs export to this machine, then verify it.

The remote side runs ``tools/export_rootfs.py`` (uploaded over ssh stdin), so this
works against any host listed in ``sshconfig.toml`` whose project lives at
``/root/hyperseg``.

On Windows, ``ssh`` is the MSYS build from Git for Windows: it is spawned through
``bash`` rather than directly, because the askpass helper that carries the password
is a shell script that only the MSYS runtime knows how to execute.

Before the archive is declared usable:

* every member stays inside the root filesystem, none is under the excluded dataset
  or a bind mount, none is transient (``tmp/``, ``run/``);
* the SHA-256 of every critical file inside the archive matches the source machine,
  which proves the archive came from that machine and is not truncated;
* ``gzip -t`` accepts the complete stream, trailer included.

Pausing and resuming
--------------------
The payload is one gzip stream, so a transfer that stops half way cannot simply
continue at a byte offset — the server has to regenerate the stream, and the client
can only append if the regenerated bytes are identical to what it already holds. That
holds here because ``export_rootfs.py`` uses ``gzip -n`` (no timestamp, no filename):
an unchanged filesystem yields a byte-identical stream.

"Unchanged" is stricter than it sounds: ``tar`` records the mtime of every file it
packs, so merely *rewriting* a file that lives inside the exported tree changes the
stream from that header onward. Hence two rules this script follows — the stream helper
is staged on the excluded data disk rather than under ``/root``, and an unchanged
``export_rootfs.py`` is left alone instead of being re-uploaded (``sync_helper``).

So there are two ways to stop:

* **Gracefully** — create the sentinel file printed at startup (``<label>.pause`` in the
  meta directory). The loop notices within a second, flushes, records a checkpoint and
  exits with ``stage=paused``. Delete the sentinel before resuming.
* **Hard** — kill the process; the ``.partial`` file is still a clean prefix of the
  stream. Record it with ``--checkpoint-only`` so the byte count is on file.

``--resume`` then regenerates the stream on the server, **proves the prefix is still
byte-identical** (``remote_export_stream.py prefix``), and transfers only the missing
tail (``remote_export_stream.py emit``). If the proof fails, the source changed and the
transfer must start over — the script says so instead of writing a corrupt archive.

Usage:
    python tools/download_rootfs.py --server server3 --label server3-system-no-dataset-20260929
    python tools/download_rootfs.py --server server3 --label ... --inspect-only
    python tools/download_rootfs.py --label ... --checkpoint-only
    python tools/download_rootfs.py --server server3 --label ... --resume
    python tools/download_rootfs.py --label ... --verify-existing
"""

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
SSHCONFIG = PROJECT / "sshconfig.toml"
REMOTE_SCRIPT = "/root/autodl-tmp/export_rootfs.py"
# Both helpers live on the excluded data disk, never under ``/root``: a submission image
# should not carry the scratch tooling used to build it, and anything written inside the
# exported tree changes the tar headers around it.
REMOTE_STREAM_DIR = "/root/autodl-tmp"
REMOTE_STREAM_SCRIPT = REMOTE_STREAM_DIR + "/remote_export_stream.py"
REMOTE_DIR = "/root/hyperseg"

BASH_CANDIDATES = [
    r"C:\Program Files\Git\bin\bash.exe",
    r"C:\Program Files (x86)\Git\bin\bash.exe",
    "/usr/bin/bash",
    "/bin/bash",
]


def find_bash():
    found = shutil.which("bash")
    if found:
        return found
    for candidate in BASH_CANDIDATES:
        if Path(candidate).exists():
            return candidate
    raise SystemExit("bash not found; install Git for Windows or pass a POSIX shell")


def posix(path):
    return str(path).replace("\\", "/")


def parse_sshconfig(name):
    text = SSHCONFIG.read_text(encoding="utf-8")
    block = re.search(rf"^\[{re.escape(name)}\]\s*$(.*?)(?=^\[|\Z)",
                      text, re.MULTILINE | re.DOTALL)
    if not block:
        raise SystemExit(f"server {name!r} not found in {SSHCONFIG}")
    body = block.group(1)
    line = re.search(r"^\s*ssh\s+-p\s+(\d+)\s+(\S+@\S+)", body, re.MULTILINE)
    password = re.search(r"^\s*password\s*=\s*(\S+)", body, re.MULTILINE)
    if not line:
        raise SystemExit(f"cannot parse the ssh line for {name!r}")
    return {"port": line.group(1), "target": line.group(2),
            "password": password.group(1) if password else ""}


class Host:
    """Non-interactive ssh without sshpass: OpenSSH 8.4+ honours
    ``SSH_ASKPASS_REQUIRE=force``, so no terminal is required."""

    def __init__(self, config, workdir, bash):
        self.bash = bash
        helper = Path(workdir) / "askpass.sh"
        # newline="\n" matters: a CRLF shebang line is not executable by bash.
        helper.write_text("#!/usr/bin/env bash\nprintf '%s\\n' "
                          + json.dumps(config["password"]) + "\n",
                          encoding="utf-8", newline="\n")
        self.askpass = posix(helper)
        self.options = ["-p", config["port"],
                        "-o", "StrictHostKeyChecking=no",
                        "-o", "UserKnownHostsFile=/dev/null",
                        "-o", "ConnectTimeout=25",
                        "-o", "NumberOfPasswordPrompts=1",
                        "-o", "ServerAliveInterval=30",
                        "-o", "ServerAliveCountMax=10",
                        config["target"]]

    def argv(self, command):
        inner = ("export SSH_ASKPASS={askpass} SSH_ASKPASS_REQUIRE=force DISPLAY=:0; "
                 "exec ssh {options} {command}").format(
            askpass=shlex.quote(self.askpass),
            options=" ".join(shlex.quote(option) for option in self.options),
            command=shlex.quote(command))
        return [self.bash, "-c", inner]

    def run(self, command, **kwargs):
        return subprocess.run(self.argv(command), **kwargs)

    def popen(self, command, **kwargs):
        return subprocess.Popen(self.argv(command), **kwargs)

    def upload(self, local, remote):
        with open(local, "rb") as stream:
            subprocess.run(self.argv(f"cat > {remote}"), stdin=stream, check=True)


def atomic_write(path, text):
    """Write via a temp file when the filesystem allows the rename.

    exFAT targets (this project keeps multi-GB artifacts on an exFAT volume) can
    reject ``os.replace`` while a scanner holds the freshly written temp file, so
    fall back to a plain overwrite instead of failing the whole transfer.
    """
    path = Path(path)
    temp = Path(str(path) + ".tmp")
    temp.write_text(text, encoding="utf-8")
    for attempt in range(4):
        try:
            temp.replace(path)
            return
        except PermissionError:
            time.sleep(0.5 * (attempt + 1))
    print(f"WARNING: rename over {path.name} rejected; overwriting in place", flush=True)
    path.write_text(text, encoding="utf-8")
    try:
        temp.unlink()
    except OSError:
        pass


def update(status_path, **values):
    values["updated_utc"] = datetime.now(timezone.utc).isoformat()
    atomic_write(status_path, json.dumps(values, indent=2) + "\n")
    print(json.dumps(values, ensure_ascii=False), flush=True)


def remote_python():
    """Prefer miniconda's interpreter, which is what the project venv expects.
    ``$PY`` is expanded by the remote shell, not by us."""
    return ("PY=/root/miniconda3/bin/python; test -x $PY || PY=python3; "
            f"cd {REMOTE_DIR} && $PY")


def verify(path, manifest, progress, bash):
    critical = manifest["critical_files"]
    found = {}
    total_bytes = members = 0
    forbidden = [p.lstrip("/") for p in manifest["excluded_paths"] if "*" not in p]
    progress(stage="verifying", archive_bytes=path.stat().st_size)
    last_update = time.monotonic()
    with tarfile.open(path, mode="r|gz") as archive:
        for member in archive:
            name = member.name
            if name.startswith("./"):
                name = name[2:]
            name = name.rstrip("/")
            if name.startswith("/") or ".." in name.split("/"):
                raise RuntimeError(f"Unexpected archive path: {name}")
            if any(name == p or name.startswith(p + "/") for p in forbidden):
                raise RuntimeError(f"Excluded path found in archive: {name}")
            if name.startswith(("tmp/", "run/")):
                raise RuntimeError(f"Transient content found in archive: {name}")
            members += 1
            if member.isfile():
                total_bytes += member.size
            key = "/" + name
            if key in critical:
                if not member.isfile():
                    raise RuntimeError(f"Critical file is not a regular file: {name}")
                digest = hashlib.sha256()
                with archive.extractfile(member) as stream:
                    for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
                        digest.update(block)
                expected = critical[key]
                if member.size != expected["size"] or digest.hexdigest() != expected["sha256"]:
                    raise RuntimeError(f"Critical file differs from the source: {name}")
                found[key] = digest.hexdigest()
                print(f"  critical ok: {key}", flush=True)
            if time.monotonic() - last_update > 30:
                progress(stage="verifying", members=members, file_bytes=total_bytes)
                last_update = time.monotonic()
    missing = set(critical) - set(found)
    if missing:
        raise RuntimeError(f"Missing critical files: {sorted(missing)}")
    # gzip -t consumes the whole stream, including the trailer after tar's EOF.
    subprocess.run([bash, "-c", f"gzip -t {shlex.quote(posix(path))}"], check=True)
    return {"members": members, "regular_file_bytes": total_bytes,
            "critical_files_verified": found, "excluded_paths_verified": True,
            "gzip_integrity_verified": True}


def digest_file(path, digest=None, block=16 * 1024 * 1024):
    """Feed an existing file into a hasher. Returns ``(digest, bytes_read)``.

    Passing a hasher lets a resumed transfer carry on from the bytes already on disk
    without reading them twice: the digest is seeded with the prefix, then extended
    with whatever the server sends next."""
    digest = digest if digest is not None else hashlib.sha256()
    size = 0
    with open(path, "rb") as stream:
        for chunk in iter(lambda: stream.read(block), b""):
            digest.update(chunk)
            size += len(chunk)
    return digest, size


def sha256_file(path):
    return digest_file(path)[0].hexdigest()


def remote_sha256(host, path):
    probe = host.run(f"sha256sum {path}", capture_output=True, text=True,
                     encoding="utf-8", errors="replace")
    if probe.returncode:
        return None
    token = probe.stdout.split()
    return token[0] if token else None


def sync_helper(host, local, remote, keep_existing=False):
    """Upload a helper script unless the server already has a copy we must not disturb.

    A redundant upload is not harmless. ``tar`` records the mtime of every file it
    packs, and ``/root/export_rootfs.py`` sits *inside* the exported root filesystem:
    rewriting it would change one tar header, which changes the gzip stream from that
    byte onward. An interrupted transfer could then never be resumed, because the bytes
    it holds would no longer be a prefix of what the server produces.

    ``keep_existing`` is for exactly that case, and it wins over the local copy: the
    archive already on disk was packed by whatever exporter was staged when the
    transfer began, so reproducing *that* script is what makes a resume possible. A
    local edit therefore takes effect on the next fresh download, not on a resume, and
    the mismatch is reported rather than silently resolved.
    """
    local_digest = sha256_file(local)
    existing = remote_sha256(host, remote)
    if existing is not None and keep_existing:
        if existing == local_digest:
            print(f"helper {remote} matches the local copy; mtime left untouched",
                  flush=True)
        else:
            print(f"WARNING: staged {remote} ({existing[:12]}...) differs from "
                  f"{local.name} ({local_digest[:12]}...). Keeping the staged copy so "
                  f"the interrupted transfer stays resumable; the local edits apply to "
                  f"the next fresh download.", flush=True)
        return False
    if existing == local_digest:
        print(f"helper {remote} already current; mtime left untouched", flush=True)
        return False
    host.upload(local, remote)
    if remote_sha256(host, remote) != local_digest:
        raise RuntimeError(f"uploaded {remote} does not hash back to the local copy")
    print(f"staged helper {remote}", flush=True)
    return True


def write_checkpoint(path, **values):
    """Merge values into the resume checkpoint and return the result.

    A checkpoint written mid-transfer carries ``partial_sha256=null`` on purpose: the
    file is still growing, so the only trustworthy prefix hash is the one computed when
    the transfer is stopped. ``--resume`` recomputes it from disk regardless."""
    checkpoint = {}
    if path.exists():
        try:
            checkpoint = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            checkpoint = {}
    checkpoint.update(values)
    checkpoint["updated_utc"] = datetime.now(timezone.utc).isoformat()
    atomic_write(path, json.dumps(checkpoint, indent=2, ensure_ascii=False) + "\n")
    return checkpoint


def stream_remainder(host, command, destination, digest, out, progress,
                     pause_flag, size, initial_size, expected_total, started):
    """Copy the remote stream into an open file until it ends or the pause flag appears.

    Returns ``(bytes_on_disk, paused)``. The remote command has to be a single program
    (``remote_export_stream.py emit``), because then its exit status is meaningful and
    a failed tar/gzip surfaces instead of looking like a short but valid stream.
    """
    transfer = host.popen(command, stdout=subprocess.PIPE)
    paused = False
    last_update = time.monotonic()
    try:
        while True:
            block = transfer.stdout.read(4 * 1024 * 1024)
            if not block:
                break
            if pause_flag is not None and pause_flag.exists():
                paused = True
                break
            if shutil.disk_usage(out).free < len(block) + 2 * 1024**3:
                raise RuntimeError("Stopping before local free space falls below 2 GiB")
            destination.write(block)
            digest.update(block)
            size += len(block)
            now = time.monotonic()
            if now - last_update > 30:
                destination.flush()
                last_update = now
                values = {"stage": "downloading", "bytes": size,
                          "elapsed_seconds": round(now - started),
                          "average_mib_s": round((size - initial_size)
                                                 / max(now - started, 1e-6) / 1024**2, 2)}
                if expected_total:
                    values["expected_total_bytes"] = expected_total
                    values["percent"] = round(100 * size / expected_total, 2)
                progress(**values)
        destination.flush()
        os.fsync(destination.fileno())
    finally:
        if transfer.poll() is None:
            transfer.terminate()
            transfer.wait()
    if not paused and transfer.returncode:
        raise RuntimeError(f"Remote export failed with exit {transfer.returncode}; "
                           f"partial kept")
    return size, paused


def probe_prefix(host, prefix_bytes):
    """Regenerate the stream on the server and hash its first ``prefix_bytes``.

    The archive is a gzip stream, so this is the only way to prove that the bytes
    already on disk are still exactly the bytes the server produces now — which is
    precisely the condition for appending to them."""
    host.run(f"mkdir -p {REMOTE_STREAM_DIR}", check=True)
    sync_helper(host, PROJECT / "tools" / "remote_export_stream.py", REMOTE_STREAM_SCRIPT)
    result = host.run(f"{remote_python()} {REMOTE_STREAM_SCRIPT} prefix "
                      f"--prefix-bytes {prefix_bytes}",
                      capture_output=True, text=True, encoding="utf-8", errors="replace")
    if result.returncode:
        raise RuntimeError(f"prefix probe failed with exit {result.returncode}: "
                           f"{result.stderr[-1500:]}")
    lines = [line for line in result.stdout.splitlines() if line.strip().startswith("{")]
    if not lines:
        raise RuntimeError(f"prefix probe produced no report: {result.stdout[-800:]}")
    return json.loads(lines[-1])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server", default="server3")
    parser.add_argument("--label", required=True,
                        help="basename of the artifacts, e.g. server3-system-no-dataset-20260929")
    parser.add_argument("--out", default=str(PROJECT),
                        help="directory for the archive itself (can be a large exFAT volume)")
    parser.add_argument("--meta", default=None,
                        help="directory for manifest/status bookkeeping; defaults to "
                             "runs/<label> inside the repository, because some sandboxes "
                             "refuse to rewrite json files outside the workspace")
    parser.add_argument("--min-free-gib", type=int, default=20)
    parser.add_argument("--verify-existing", action="store_true",
                        help="re-verify an archive that is already on disk (no ssh)")
    parser.add_argument("--inspect-only", action="store_true",
                        help="fetch and print the source manifest without downloading")
    parser.add_argument("--checkpoint-only", action="store_true",
                        help="hash the existing .partial and record a resume checkpoint "
                             "(no ssh); use after a hard stop")
    parser.add_argument("--resume", action="store_true",
                        help="continue an interrupted transfer: prove the prefix on disk "
                             "is still byte-identical, then fetch only the missing tail")
    parser.add_argument("--skip-prefix-check", action="store_true",
                        help="with --resume: skip the byte-for-byte prefix proof "
                             "(faster, but a changed source then yields a corrupt archive)")
    parser.add_argument("--pause-file", default=None,
                        help="defaults to <meta>/<label>.pause; the transfer stops as "
                             "soon as this file exists")
    args = parser.parse_args()

    out = Path(args.out)
    meta = Path(args.meta) if args.meta else PROJECT / "runs" / args.label
    archive = out / f"{args.label}.rootfs.tar.gz"
    partial = Path(str(archive) + ".partial")
    manifest_path = meta / f"{args.label}.manifest.json"
    status_path = meta / f"{args.label}.status.json"
    checkpoint_path = meta / f"{args.label}.resume.json"
    pause_flag = Path(args.pause_file) if args.pause_file else meta / f"{args.label}.pause"

    def progress(**values):
        update(status_path, **values)

    bash = find_bash()

    if args.checkpoint_only:
        if not partial.exists():
            raise SystemExit(f"no partial file at {partial}")
        digest, size = digest_file(partial)
        checkpoint = write_checkpoint(
            checkpoint_path, label=args.label, partial=posix(partial), bytes=size,
            partial_sha256=digest.hexdigest(), stage="paused", expected_total_bytes=None)
        print(json.dumps(checkpoint, indent=2, ensure_ascii=False), flush=True)
        print(f"\npaused at {size} bytes ({size / 1024**3:.2f} GiB); "
              f"delete {pause_flag.name} if present, then rerun with --resume", flush=True)
        return

    if args.verify_existing:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        verification = verify(archive, manifest, progress, bash)
        digest = sha256_file(archive)
        manifest.update(archive=archive.name, compressed_bytes=archive.stat().st_size,
                        sha256=digest, verification=verification)
        atomic_write(manifest_path, json.dumps(manifest, indent=2) + "\n")
        atomic_write(meta / (archive.name + ".sha256"), f"{digest}  {archive.name}\n")
        progress(stage="complete", archive=archive.name, bytes=archive.stat().st_size,
                 sha256=digest, verification_requested="manual")
        return

    if args.resume:
        if archive.exists():
            raise SystemExit(f"{archive} already exists; nothing to resume")
        if not partial.exists():
            raise SystemExit(f"no partial file to resume at {partial}")
    elif archive.exists() or partial.exists():
        raise SystemExit(f"{partial if partial.exists() else archive} already exists; "
                         f"pass --resume to continue it, or move it aside to start over")

    free = shutil.disk_usage(out).free
    if free < args.min_free_gib * 1024**3:
        raise SystemExit(f"Need {args.min_free_gib} GiB free in {out}; "
                         f"only {free / 1024**3:.1f} GiB available")
    out.mkdir(parents=True, exist_ok=True)
    meta.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="rootfs-transfer-") as workdir:
        host = Host(parse_sshconfig(args.server), workdir, bash)
        probe = host.run("hostname; df -h / | tail -1", capture_output=True,
                         text=True, encoding="utf-8", errors="replace")
        if probe.returncode:
            raise SystemExit(f"ssh probe failed: {probe.stderr[-1500:]}")
        print(probe.stdout.strip(), flush=True)
        sync_helper(host, PROJECT / "tools" / "export_rootfs.py", REMOTE_SCRIPT,
                    keep_existing=args.resume)

        progress(stage="source_manifest")
        inspected = host.run(f"{remote_python()} {REMOTE_SCRIPT} inspect",
                             capture_output=True, text=True, encoding="utf-8",
                             errors="replace")
        if inspected.returncode:
            raise SystemExit(f"Source inspection failed: {inspected.stderr[-2000:]}")
        manifest = json.loads(inspected.stdout)
        # Read the earlier manifest before it is overwritten: --resume compares the two
        # to catch a source that changed between the pause and the continue.
        previous_manifest = None
        if manifest_path.exists():
            try:
                previous_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            except ValueError:
                previous_manifest = None
        atomic_write(manifest_path, json.dumps(manifest, indent=2) + "\n")
        print(f"excluded {len(manifest['excluded_paths'])} paths; "
              f"critical {len(manifest['critical_files'])} files", flush=True)
        if manifest["missing_critical"]:
            print("WARNING missing critical:", manifest["missing_critical"], flush=True)
        if not manifest["critical_files"]:
            raise SystemExit("No critical files found on the source machine")
        if args.inspect_only:
            print(json.dumps(manifest, indent=2, ensure_ascii=False)[:6000], flush=True)
            return

        start = time.monotonic()
        expected_total = None
        initial_size = 0
        digest = hashlib.sha256()

        if args.resume:
            checkpoint = {}
            if checkpoint_path.exists():
                try:
                    checkpoint = json.loads(checkpoint_path.read_text(encoding="utf-8"))
                except ValueError:
                    checkpoint = {}
            size_on_disk = partial.stat().st_size
            recorded = checkpoint.get("bytes")
            if recorded not in (None, size_on_disk):
                raise SystemExit(
                    f"checkpoint records {recorded} bytes but {partial.name} holds "
                    f"{size_on_disk}; something else wrote to the file, so the prefix "
                    f"cannot be trusted. Start over instead of resuming.")
            if (previous_manifest
                    and previous_manifest.get("critical_files") != manifest["critical_files"]):
                raise SystemExit("Critical files differ from the earlier run, so the source "
                                 "changed. Start over instead of resuming.")

            progress(stage="hashing_partial", bytes=size_on_disk)
            print(f"hashing the {size_on_disk / 1024**3:.2f} GiB already on disk...",
                  flush=True)
            digest, initial_size = digest_file(partial, digest)
            if initial_size != partial.stat().st_size:
                raise SystemExit("the partial changed while it was being hashed; retry")
            if checkpoint.get("partial_sha256") not in (None, digest.hexdigest()):
                raise SystemExit("the partial no longer matches the hash recorded when it "
                                 "was paused. Start over instead of resuming.")
            size = initial_size
            expected_total = checkpoint.get("expected_total_bytes")

            if args.skip_prefix_check:
                if not expected_total:
                    print("WARNING: no recorded stream length; only the final verification "
                          "can prove the archive is complete", flush=True)
            else:
                progress(stage="verifying_prefix", bytes=size)
                print("regenerating the stream on the server to prove the prefix matches...",
                      flush=True)
                report = probe_prefix(host, size)
                expected_total = report["total_bytes"]
                if report["prefix_sha256"] != digest.hexdigest():
                    raise SystemExit(
                        "the regenerated stream differs from the bytes already on disk "
                        f"(server {report['prefix_sha256'][:16]}... vs local "
                        f"{digest.hexdigest()[:16]}...), so the two halves would not join. "
                        "Start over instead of resuming.")
                print(f"prefix proof ok: {size} bytes match byte for byte; the full stream "
                      f"is {expected_total} bytes ({report['elapsed_seconds']}s to "
                      f"regenerate on the server)", flush=True)

            write_checkpoint(checkpoint_path, label=args.label, partial=posix(partial),
                             bytes=size, partial_sha256=digest.hexdigest(),
                             expected_total_bytes=expected_total, stage="resuming")
            command = f"{remote_python()} {REMOTE_STREAM_SCRIPT} emit --skip-bytes {size}"
            open_mode = "ab"
        else:
            size = 0
            write_checkpoint(checkpoint_path, label=args.label, partial=posix(partial),
                             bytes=0, partial_sha256=None, stage="downloading")
            command = f"{remote_python()} {REMOTE_SCRIPT} export"
            open_mode = "xb"

        if pause_flag.exists():
            raise SystemExit(f"pause sentinel {pause_flag} exists; delete it to transfer")

        def report(**values):
            progress(**values)
            if "bytes" in values:
                # partial_sha256 is cleared on purpose: the file is still growing, so the
                # only prefix hash worth recording is the one taken while it is frozen.
                write_checkpoint(checkpoint_path, bytes=values["bytes"],
                                 partial_sha256=None, stage=values.get("stage"))

        progress(stage="downloading", bytes=size, expected_total_bytes=expected_total)
        with partial.open(open_mode) as destination:
            size, paused = stream_remainder(
                host, command, destination, digest, out, report, pause_flag,
                size, initial_size, expected_total, start)

        if paused:
            write_checkpoint(checkpoint_path, label=args.label, partial=posix(partial),
                             bytes=size, partial_sha256=None, stage="paused",
                             expected_total_bytes=expected_total)
            progress(stage="paused", bytes=size, partial=posix(partial))
            print(f"paused at {size} bytes ({size / 1024**3:.2f} GiB). Re-run with "
                  f"--resume to continue.", flush=True)
            return

        if expected_total and size != expected_total:
            write_checkpoint(checkpoint_path, label=args.label, partial=posix(partial),
                             bytes=size, partial_sha256=None, stage="incomplete",
                             expected_total_bytes=expected_total)
            raise SystemExit(f"received {size} of {expected_total} bytes; "
                             f"{partial.name} is kept, re-run with --resume")

        verification = verify(partial, manifest, progress, bash)
        for attempt in range(6):
            try:
                partial.replace(archive)
                break
            except PermissionError:
                time.sleep(1 + attempt)
        else:
            raise SystemExit(f"could not rename {partial.name} to {archive.name}; the "
                             f"partial is intact, rename it by hand")
        elapsed = round(time.monotonic() - start)
        digest_hex = digest.hexdigest()

    atomic_write(meta / (archive.name + ".sha256"),
                 f"{digest_hex}  {archive.name}\n")
    manifest.update(archive=str(archive), compressed_bytes=size,
                    sha256=digest_hex, verification=verification)
    atomic_write(manifest_path, json.dumps(manifest, indent=2) + "\n")
    write_checkpoint(checkpoint_path, label=args.label, archive=posix(archive),
                     bytes=size, partial_sha256=None, stage="complete",
                     expected_total_bytes=size, sha256=digest_hex)
    progress(stage="complete", archive=archive.name, bytes=size, sha256=digest_hex,
             elapsed_seconds=elapsed)


if __name__ == "__main__":
    def flag(name, default):
        for index, token in enumerate(sys.argv):
            if token == name and index + 1 < len(sys.argv):
                return sys.argv[index + 1]
            if token.startswith(name + "="):
                return token.split("=", 1)[1]
        return default

    try:
        main()
    except BaseException as exc:
        label = flag("--label", None)
        if label:
            stage = "verification_failed" if "--verify-existing" in sys.argv else "failed"
            meta = flag("--meta", None)
            status = (Path(meta) if meta else PROJECT / "runs" / label) / f"{label}.status.json"
            try:
                update(status, stage=stage, error=str(exc))
            except OSError:
                pass
        raise
