"""Dump the tar members of a truncated export stream, attributes included.

A paused transfer leaves a clean *prefix* of the export stream. Comparing that prefix
against the machine it came from is the only way to tell whether the stream can be
regenerated byte for byte, which is the precondition for appending to it. The comparison
has to cover every attribute the archive recorded, and GNU tar in ``--format=pax`` mode
records three timestamps per member — ``mtime``, ``atime`` and ``ctime`` — each with
nanosecond precision in an extended header. ``atime`` is the dangerous one: reading a
file updates it, and packing the filesystem reads every file, so a stream is only
reproducible if the mount suppresses access-time updates.

Usage:
    python tools/inspect_partial_stream.py <partial> --dump-json entries.json
    python tools/inspect_partial_stream.py <partial> --filter /root --tail 20
"""

import argparse
import json
import tarfile
from pathlib import Path


def member_type(member):
    if member.isdir():
        return "dir"
    if member.issym():
        return "symlink"
    if member.islnk():
        return "hardlink"
    if member.isreg():
        return "file"
    return "other"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("partial")
    parser.add_argument("--filter", default="/root",
                        help="only print members whose archive path contains this")
    parser.add_argument("--tail", type=int, default=30)
    parser.add_argument("--dump-json", default=None,
                        help="write every parsed member to this file, for comparison "
                             "against the live tree it was packed from")
    args = parser.parse_args()

    path = Path(args.partial)
    print(f"file: {path}")
    print(f"bytes on disk: {path.stat().st_size}")

    members = []
    stopped = None
    with open(path, "rb") as handle:
        try:
            with tarfile.open(fileobj=handle, mode="r|*") as archive:
                for member in archive:
                    members.append(member)
        except Exception as exc:  # noqa: BLE001 - a truncated stream is the expected case
            stopped = exc

    print(f"members parsed: {len(members)}")
    if stopped is not None:
        print(f"stream ends early: {type(stopped).__name__}: {stopped}")
    else:
        print("stream parsed to the end of the tar (no truncation seen)")
    print(f"payload bytes described: {sum(m.size for m in members)}")

    if args.dump_json:
        dump = [{
            "name": m.name,
            "type": member_type(m),
            "size": m.size,
            "mode": oct(m.mode),
            "uid": m.uid,
            "gid": m.gid,
            "mtime": m.mtime,
            "pax": m.pax_headers or {},
        } for m in members]
        Path(args.dump_json).write_text(json.dumps(dump, indent=1), encoding="utf-8")
        print(f"dumped {len(dump)} entries to {args.dump_json}")

    print(f"\n--- last {min(args.tail, len(members))} members (walk order) ---")
    for m in members[-args.tail:]:
        print(f"{m.name}  {member_type(m)}  size={m.size}  mtime={m.mtime}")

    interesting = [m for m in members if args.filter in m.name]
    print(f"\n--- {len(interesting)} members containing {args.filter!r} ---")
    for m in interesting[:args.tail]:
        print(f"{m.name}  {member_type(m)}  size={m.size}  pax={m.pax_headers or {}}")


if __name__ == "__main__":
    main()
