"""Runs **on the server**: regenerate the rootfs export stream and report two things
in a single pass — the SHA-256 of its first ``--prefix-bytes`` bytes, and the total
stream length.

Why this exists: the archive is a single gzip stream, so an interrupted transfer can
only be resumed by regenerating the stream from the beginning and discarding what was
already received. That is only safe if the regenerated bytes are *identical* to what
the earlier run produced, which is what the prefix hash proves. ``export_rootfs.py``
compresses with ``gzip -n`` (no timestamp, no filename), so an unchanged filesystem
yields a byte-identical stream.

Usage:
    python probe_export_stream.py --prefix-bytes 6124826624
"""

import argparse
import hashlib
import json
import subprocess
import sys
import time

BLOCK = 4 * 1024 * 1024


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix-bytes", type=int, required=True,
                        help="hash this many leading bytes of the stream")
    parser.add_argument("--exporter", default="/root/export_rootfs.py")
    args = parser.parse_args()

    python = sys.executable
    started = time.monotonic()
    process = subprocess.Popen([python, args.exporter, "export"],
                               stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)

    digest = hashlib.sha256()
    total = 0
    hashed = 0
    try:
        while True:
            block = process.stdout.read(BLOCK)
            if not block:
                break
            if hashed < args.prefix_bytes:
                take = block[:args.prefix_bytes - hashed]
                digest.update(take)
                hashed += len(take)
            total += len(block)
    finally:
        process.stdout.close()
        if process.poll() is None:
            process.terminate()
        process.wait()

    print(json.dumps({
        "prefix_bytes": hashed,
        "prefix_sha256": digest.hexdigest(),
        "total_bytes": total,
        "elapsed_seconds": round(time.monotonic() - started, 1),
        "exporter_exit_code": process.returncode,
    }), flush=True)


if __name__ == "__main__":
    main()
